### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by philippReist**

### CODE REVIEW

**Comment by ray-hrst** [comment]
@philippReist something's strange. The build tests for Ubuntu and Window are getting stuck building the Qt environment. I don't really have time to debug this at the moment, but I'll take a look hopefully later today or tomorrow. Is there a deadline?

**Comment by philippReist** [comment]
No deadline, thank you for checking it. Will the deployment packages be built as well? This is V1.0.0, yay!

**Comment by ray-hrst** [comment]
The [issue](https://github.com/jurplel/install-qt-action/issues/27#issuecomment-586658469) was with a dependency in the Qt build environment. I've added a workaround, but I should change it once the issue is resolved, see #55.

Everything seems to be building and passing now. I've attached the binaries, which I've compiled in a sandbox for user testing.. strange that the binary for Ubuntu is 20
[dancebots-editor-ubuntu.tar.gz](https://github.com/philippReist/dancebots_gui/files/4249764/dancebots-editor-ubuntu.tar.gz)
x smaller than the one for macOS. I've also noticed that this binary for macOS will only work on macOS 10.15. My macbook uses 10.14.. Give me a few days to user test this.

FYI. After you merge, the deployment packages will be build and automatically uploaded to the release for Ubuntu and macOS only. I never got around to setting this up for Windows yet -- sorry.

[dancebots-editor-darwin.zip](https://github.com/philippReist/dancebots_gui/files/4249758/dancebots-editor-darwin.zip)
[dancebots-editor-ubuntu.tar.gz](https://github.com/philippReist/dancebots_gui/files/4249769/dancebots-editor-ubuntu.tar.gz)

**Comment by philippReist** [comment]
No worries, can deploy win manually. Thanks for fixing the build!

**Pull request merged**
